AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Application.
Parameters:
  SecurityGroupId:
    Type: 'AWS::EC2::SecurityGroup::Id'
  SubNetId1:
    Type: 'AWS::EC2::Subnet::Id'
  SubNetId2:
    Type: 'AWS::EC2::Subnet::Id'
  EnvironmentType:
    Description: The environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod
    ConstraintDescription: 'Must be dev, uat or prod'
Mappings:
  EnvironmentVariablesMap:
    Function.Properties.CodeUri.Bucket:
      dev: vanlune-bin-dev
      uat: vanlune-bin-uat
      prod: vanlune-bin-prod
    Function.Properties.Products.Bucket:
      dev: vanlune-products-dev
      uat: vanlune-products-uat
      prod: vanlune-products-prod
    Stage.ApiGateway:
      dev: Dev
      uat: Uat
      prod: Prod
Resources:
 # API Functinos
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !FindInMap 
          - EnvironmentVariablesMap
          - Stage.ApiGateway
          - !Ref EnvironmentType
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  CreateOrUpdatProduct:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: vanlune-product-create-update
      Handler: >-
        Products.Application::Products.Application.Function::CreateOrUpdateProducts
      Runtime: dotnetcore3.1
      CodeUri:
        Bucket: !FindInMap 
          - EnvironmentVariablesMap
          - Function.Properties.CodeUri.Bucket
          - !Ref EnvironmentType
        Key: Products.zip
      MemorySize: 256
      Timeout: 900
      Role: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/role-lambda-vanlune']]
      Policies:
        - AWSLambdaBasicExecutionRole
      Tracing: Active
      Events:
        HttpPost: 
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: '/product'
            Method: post        
      Environment:
        Variables:
          AWS_S3_Bucket: !FindInMap 
            - EnvironmentVariablesMap
            - Function.Properties.Products.Bucket
            - !Ref EnvironmentType
  DeleteProduct:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: vanlune-product-delete
      Handler: >-
        Products.Application::Products.Application.Function::DeleteProducts
      Runtime: dotnetcore3.1
      CodeUri:
        Bucket: !FindInMap 
          - EnvironmentVariablesMap
          - Function.Properties.CodeUri.Bucket
          - !Ref EnvironmentType
        Key: Products.zip
      MemorySize: 256
      Timeout: 900
      Role: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/role-lambda-vanlune']]
      Policies:
        - AWSLambdaBasicExecutionRole
      Tracing: Active
      Events:
        HttpPost: 
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: '/product'
            Method: delete
      Environment:
        Variables:
          AWS_S3_Bucket: !FindInMap 
            - EnvironmentVariablesMap
            - Function.Properties.Products.Bucket
            - !Ref EnvironmentType
  GetAllProductsByCategory:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: vanlune-product-get-all
      Handler: >-
        Products.Application::Products.Application.Function::GetAllProductsByCategory
      Runtime: dotnetcore3.1
      CodeUri:
        Bucket: !FindInMap 
          - EnvironmentVariablesMap
          - Function.Properties.CodeUri.Bucket
          - !Ref EnvironmentType
        Key: Products.zip
      MemorySize: 256
      Timeout: 900
      Role: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/role-lambda-vanlune']]
      Policies:
        - AWSLambdaBasicExecutionRole
      Tracing: Active
      Events:
        HttpPost: 
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: '/product'
            Method: get
      Environment:
        Variables:
          AWS_S3_Bucket: !FindInMap 
            - EnvironmentVariablesMap
            - Function.Properties.Products.Bucket
            - !Ref EnvironmentType
  